name: web_multiple_tab_detector
description: This package makes it possible to detect how many browser tabs in the webbrowser your flutter app is currently running in.
version: 0.3.0
homepage: https://famedly.com
repository: https://gitlab.com/famedly/libraries/web_multiple_tab_detector

environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  web: ^1.1.1
dev_dependencies:
  import_sorter: ^4.6.0
